### ISSUE TITLE
Upgrade Semantic UI from 0.16.1 to Latest Version

### ISSUE THREAD

**Issue by corey-hammerton** [voxpupuli/puppetboard#178]
We are using a year and a half old version of semantic UI and there are many new features and fixes in the latest 2.1.5 release.

One possible benefit is a mobile-friendly UI.

**Comment by octomike** [comment]
I started working on this, mainly because I was curious to play around with Semantic UI and get to know puppetboard better. Still I'm too afraid to PR because I probably did a couple of things wrong :smile:

But it might help you anyways: https://github.com/octomike/puppetboard/tree/semantic_update

It's pretty close to the original layout while staying with semantic defaults. 

![pb-semantic2 1 6_01](https://cloud.githubusercontent.com/assets/5805185/11562663/a97587fe-99cf-11e5-86db-275964fa33fa.png)

I made some changes in the facts view template to be more readable on mobile.

![pb-semantic2 1 6_02](https://cloud.githubusercontent.com/assets/5805185/11562675/b7211ecc-99cf-11e5-9dae-e4b6444975c6.png)


Note that semantic is still missing a nice way to collapse a menu that switched to stacked view.

**Comment by johnzimm** [comment]
Those fact boxes with ribbons look nice.

**Comment by corey-hammerton** [comment]
@octomike Can you implement a packaged instance of Semantic UI, i.e. using ``*.min.css`` or ``*.min.js`` files and all packages into one file?

I cannot view the full comparison between your branch and the master because there are too many differences.

**Comment by octomike** [comment]
@corey-hammerton I got rid of most useless src files but kept the themes/ folder, because I thought at some point it might be nice to set a theme in settings.py.

**Comment by corey-hammerton** [comment]
@octomike Thanks for your work. One more thing can you remove the symlinks under static/{css,js} for semantic.min.{css,js} and directly reference them in layout.html?

**Comment by octomike** [comment]
Like this?
Wasn't sure about jquery.min.map though..

**Comment by corey-hammerton** [comment]
@octomike If you like you can create a Pull Request with your work here. I will create a branch that will be used for a 0.2.x series release.

**Comment by corey-hammerton** [comment]
Fixed by https://github.com/voxpupuli/puppetboard/pull/211
