### ISSUE TITLE
Unsafe content warning when deploying over HTTPS

### ISSUE THREAD

**Issue by mlocher** [voxpupuli/puppetboard#46]
The warning is because the 'flatly' theme for bootswatch includes a google font via a HTTP link. The file in question is the following, the import statement is at the very top.

https://netdna.bootstrapcdn.com/bootswatch/2.3.2/flatly/bootstrap.min.css

I know, this is not an issue with puppetboard itself, but I thought to report it anyway, maybe somebody knows an easy fix! (Not loading the font file is an easy fix, but produces some layout glitches.)

**Comment by rmacian** [comment]
I have another effect due to external css references. I've installed puppetboard on a server with no Internet access connection, so the style is messed up

http://netdna.bootstrapcdn.com/bootswatch/2.3.2/flatly/bootstrap.min.css
http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css
http://code.jquery.com/jquery-1.10.0.min.js
http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js
http://cdn.jsdelivr.net/tablesorter/2.0.3/jquery.tablesorter.min.js
