### ISSUE TITLE
Inventory OS column blank on all nodes running Centos 7

### ISSUE THREAD

**Issue by ebdavison** [voxpupuli/puppetboard#485]
I have 7 nodes running CentOS and 1 running Ubuntu and none of the CentOS nodes are displaying a value in the OS column on the inventory screen.
Puppet: 6.0
PuppetDB: 6.0
puppetboard: 0.3.0, installed manually and running on Apache with Mod-WSGI

**Comment by ebdavison** [comment]
More digging shows the values for OS that is being used is the fact lsbdistdescription, which for CentOS does not seem to be populated.

Maybe something like this would work (better?):

app.py
273c273
<                      ('OS', "%s %s" % (operatingsystem, operatingsystemtrelease)),
---
>                      ('OS', 'lsbdistdescription'),

**Comment by jrau9115** [comment]
Adding my own information to this bug as we recently started using Puppetboard and I noticed the same issue. The OS column appears to work for Debian based operating systems because of what facts it's trying to pull to get the OS. RedHat, CentOS, and Fedora don't show up in the list at all. 

While looking into this myself I can't seem to find where this is getting set, as modifying app.py doesn't seem to change anything, so I'm guessing it's getting overloaded deeper into the program. Regardless, I'll try taking a stab at getting this working, as my OCD acts up seeing only half our inventory showing the proper data in the OS column.

**Comment by ffalor** [comment]
Looks like it's being set [here](https://github.com/voxpupuli/puppetboard/blob/3b35403cba15a3f93d55965050abb4048b0a73b4/puppetboard/app.py#L299)

I haven't tried it, but based on the code and readme we can overwrite it by providing a value for `INVENTORY_FACTS`

The readme just says to provide a list of tuples, if you want to see how they are generating it you can view the code [here](https://github.com/voxpupuli/puppetboard/blob/3b35403cba15a3f93d55965050abb4048b0a73b4/puppetboard/docker_settings.py#L76)

Also `os.description` fact should have the similar/same output as `lsbdistdescription` and work for all OS's. Perhaps that should be the default.
